_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "3":
                - 2
                - 13
                - 14
                - 15
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.5
            "6": 4.48.2
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
batch_size:
    value: 2
learning_rate:
    value: 5e-05
max_length:
    value: 2048
num_train_epochs:
    value: 4
warmup_steps:
    value: 20
